name: Build App

on:
  push:
    branches: [ compare_bgp ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install Deps
        run: npm ci
      - name: Build Vue App
        run: npm run build

      # upload all build artefacts
      - uses: actions/upload-artifact@v2
        with:
          name: routinator-ui-build
          path: dist/
