name: Release App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install Deps
        run: npm ci
      - name: Build Vue App
        run: npm run build
      - name: Release App
        uses: softprops/action-gh-release@v1
        with:
          # This filename is deteremined by the Webpack Filemanager 
          # plugin in vue.config.js and contains all files in /dist
          # *with* the original directory structure.
          files: routinator-ui-build.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
