name: Test S3

on:
  push:
    branches: [ release-v0.2.4 ]
  jobs:
    sync-aws-s3-bucket:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_S3_REGION }}
            SOURCE_DIR: "dist"
        - name: create files list
          working-directory: dist
          run: echo `ls -pd * | grep -v /; ls -pd */*` > .files
        - name: invalidate
          uses: chetan/invalidate-cloudfront-action@master
          env:
            DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
            PATHS_FROM: .files
            AWS_REGION: ${{ secrets.AWS_S3_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
